version: '3.8'

services:

  app:
    build: .
    ports:
      - "8080:8080"

  postgres:
    image: postgres
    environment:
      POSTGRES_DB: auditdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

  redis:
    image: redis
    ports:
      - "6379:6379"